### ISSUE TITLE
Space between iframe and top bar

### ISSUE THREAD

**Issue by grigorii-horos** [messagerie-melanie2/Roundcube-Plugin-ownCloud#10]
I use Larry mod theme with smapp top bar

![screenshot_20160718_163819](https://cloud.githubusercontent.com/assets/4980269/16916562/14d2eb56-4d06-11e6-9ce7-2bf2b6abb05e.png)

**Comment by tpayen** [comment]
I don't know smapp top bar, but you can probably try to edit skin/larry/frame.css file and remove top position for #mainscreen : https://github.com/messagerie-melanie2/Roundcube-Plugin-ownCloud/blob/master/skins/larry/frame.css#L7

**Comment by grigorii-horos** [comment]
@tpayen This isn't good solution, but I changed css and now owncloud look: 
![screenshot_20160718_202040](https://cloud.githubusercontent.com/assets/4980269/16923868/2b679802-4d25-11e6-8179-970ff1a46400.png)
