### ISSUE TITLE
Login without domain part

### ISSUE THREAD

**Issue by grigorii-horos** [messagerie-melanie2/Roundcube-Plugin-ownCloud#11]
I have ~100 users in roundcube and owncloud with same password, but roundcube logins is `login@domail.ltd`, but in owncloud only `login`.
You can add possibility to remove domain part from login?
For example, if present

``` php
$config['username_domain'] = 'domain.ltd';
```

in `config.inc.php`

**Comment by mckaygerhard** [comment]
there's a configuracin in roundcube that u can made assumed the domain part.. and pass to oc.. so this are so not necesary a feaure request, only u must configure better the roundcube instalation
