### ISSUE TITLE
Where can I find roundcube_external ? 

### ISSUE THREAD

**Issue by ychaouche** [messagerie-melanie2/Roundcube-Plugin-ownCloud#8]
Can't find roundcube_external. I'm sure I'm being stupid but is this supposed to be an owncloud app that I can download somewhere along with this roundcube plugin ?

**Comment by tpayen** [comment]
roundcube_external app is in the owncloud directory of this plugin : https://github.com/messagerie-melanie2/Roundcube-Plugin-ownCloud/tree/master/owncloud

**Comment by ychaouche** [comment]
duh
