### ISSUE TITLE
Owncloud and roundcube on separate servers

### ISSUE THREAD

**Issue by ychaouche** [messagerie-melanie2/Roundcube-Plugin-ownCloud#9]
Hello,
How do I go about configuring this plugin if owncloud is on a physically different server than roundcube ? -roundcube on 10.10.10.20 and owncloud on 10.10.10.82-

roundcube is reachable at messagerie.mydoamin.tld and owncloud is reachable at cloud.mydomain.tld.

**Comment by tpayen** [comment]
Can you make a redirect with apache/nginx from Roundcube to ownCloud with an url like messagerie.mydomain.tld/cloud ? Just for the plugin configuration (you can keep  cloud.mydomain.tld url for a direct access to ownCloud)
It's easier if Roundcube and ownCloud share the same domain name. Because if not, you'll need to implement CORS (https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) and you'll probably need to edit ownCloud code for this.

**Comment by ychaouche** [comment]
thanks @tpayen will look in that direction.

**Comment by ychaouche** [comment]
Here's the setup that worked for me.

# Owncloud with a Reverse Proxy

The purpose of setting up a reverse proxy is to make urls look different. Some may prefer URL rewriting but since there is no need to do any if conditions or URL matching, a reverse proxy seems to fit perfectly for this job.

So we want http://cloud.domain.tld to appear as http://roundcube.domain.tld/cloud to circumvent the CSRF browser protection.

First, let's setup our roundcube's apache server to act as a reverse proxy for owncloud : 

## On the roundcube server

Add these directives to your roundcube vhost to make it act as a reverse proxy for owncloud when looking for the **/cloud** URL.

```
  ProxyPass  "/cloud/" "http://cloud.example.com/"
  ProxyPassReverse "/cloud/" "http://cloud.example.com/"

  # The ProxyRequests directive should usually be set off when using ProxyPass.
  # src:https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypass          
  ProxyRequests off

  # https://httpd.apache.org/docs/current/mod/mod_proxy.html#proxypreservehost \
  # This option should normally be turned Off.                                  
  ProxyPreserveHost off
```

## On the owncloud server

You need to explicitly add the trusted proxies, also you need to override the webroot, otherwise it won't work because the [URLs will be malformed](http://serverfault.com/questions/783863/many-404-urls-when-using-mod-proxy-html).

```
<?php
$CONFIG = array (
  # for roundcube owncloud plugin                                                     
  # https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/reverse_pro\
xy_configuration.html                                                       
  "overwritewebroot"  => "/cloud",          
  'trusted_proxies' => array ('10.10.10.20','10.10.10.19'),
  'roundcube_owncloud_des_key' => 'some des key',
...
)
```

# Caveats

The downside of this is that the original http://cloud.example.com won't work again because of the overriden webroot.

**Comment by tpayen** [comment]
Wow nice work, can I use it in the readme file ?

> The downside of this is that the original http://cloud.example.com won't work again because of the overriden webroot. 

Yes that's the problem, maybe you can rewrite http://cloud.example.com to http://cloud.example.com/cloud ?

**Comment by ychaouche** [comment]
> Wow nice work

Thanks !

> can I use it in the readme file ?

My pleasure.

> maybe you can rewrite http://cloud.example.com to http://cloud.example.com/cloud ?

At the moment I will be busy looking at roundrive. I was expecting this plugin to offer a minimal interaction between the two platforms, it seems it only displays owncloud inside of roundcube ? Is there any other benefit besides the automatic login ?

**Comment by tpayen** [comment]
> At the moment I will be busy looking at roundrive. I was expecting this plugin to offer a minimal interaction between the two platforms, it seems it only displays owncloud inside of roundcube ? Is there any other benefit besides the automatic login ? 

This plugin does the automatic login and can intercept click on ownCloud URL in email. But yes that's all.
Interractions between Roundcube and ownCloud are made in roundrive (but using WebDAV). But roundrive is just a start right now, and is not really optimized yet.
